spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: peng
    password: 123
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
